token:
  1:
    address: '0x5cAf454Ba92e6F2c929DF14667Ee360eD9fD5b26'
    chainId: 1
    decimals: 18
    logoURI: /mnt/iverse/nanoverse/data/DIM/Projects/Worldbridger/3_Work/1_DELTA/worldbridger/web3/protocols/d/_data_/img/1dev.png
    name: Dev
    symbol: DEV
    type: ERC20
